### ISSUE TITLE
Typo in for_everyone_part_ii ?

### ISSUE THREAD

**Issue by MAccadia** [PagerDuty/security-training#35]
I'm not a native English speaker but it seems there is a typo in docs/for_everyone_part_ii/index.md

> What is your business continuity plan in the **even** of a global pandemic?

I think _event_ is more appropriate here.

**Comment by richadams** [comment]
Hi @MAccadia,

You're right, that's a typo. I'll get it fixed in the next update.

Also, oof, that section didn't age well. I'll also add a little aside block to address that.

Thanks for the report!

**Comment by richadams** [comment]
This was fixed in https://github.com/PagerDuty/security-training/pull/41
