### ISSUE TITLE
pagerduty_security_training_for_everyone_part_ii_public asset not usable

### ISSUE THREAD

**Issue by schneiderj13** [PagerDuty/security-training#37]
The pagerduty_security_training_for_everyone_part_ii_public.key  Keynote presentation is not downloadable. Is it possible to update the asset again? File size is 134 bytes and seems to be either corrupt or not uploaded successfully.

**Comment by richadams** [comment]
What the... that's really weird. Thanks for letting us know!

While I figure out why the public site is showing something different, you can grab the file direct from the repo here https://github.com/PagerDuty/security-training/blob/master/docs/assets/keynote/pagerduty_security_training_for_everyone_part_ii_public.key

I suspect this is something to do with our deployment pipeline not playing nice with Git LFS.

**Comment by richadams** [comment]
I manually re-deployed the site and it should all be good now 👍 

I'll keep this ticket open so I remember to fix the underlying issue with the deployment process.

**Comment by schneiderj13** [comment]
Thank you @richadams. I downloaded the whole repo prior to submitting the issue, and the file showed as 134bytes.

![image](https://user-images.githubusercontent.com/11235068/102661713-6a7f1c80-414b-11eb-8790-9c3135d1c5b9.png)

Your link above worked perfectly and I have the file now. 

I appreciate the quick response and thanks again providing the content.

**Comment by richadams** [comment]
> I'll keep this ticket open so I remember to fix the underlying issue with the deployment process.

#39 added Git LFS support to our deployment pipeline, so closing this out now.
